import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/globals.css'

//fonts
import { Inter as FontSans } from "next/font/google"

//dark mode
import { ThemeProvider } from "@/components/theme-provider"


import { cn } from "@/lib/utils"




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
        //font
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
